---
output:
  pdf_document:
    citation_package: natbib
    fig_caption: yes
    template: ./resources/aog-latex-ms.tex
  word_document:
    reference_docx: ./resources/aog_word_style.docx
fontfamily: mathpazo
fontsize: 11pt
anonymous: false
endnotes: false
pagenumber: 1
bibliography: ../project.bib
biblio-style: ./resources/ajs.bst
title: "The Title"
author:
- affiliation: University of Oregon, Sociology
  name: Aaron Gullickson
- affiliation: University of Oregon, Sociology
  name: Erik Rummell
keywords: Sports, gender, inequality, media, public universities
thanks: Thank you to my mom for being way more driven than I am; her overcoming of lifes obstacles is nothing short of remarkable and inspiring and serves as a reminder that I am perfectly capable of achieving my own personal goals. Thank you to the wonderful teachers I have had over the years (Mr. Sweet, Mrs. Petersen, Professor Tsunokai, Professor Gillham, Professor Czopp, & Professor Graham, probably more of you!) Thank you to Aaron Gullickson for teaching me not only how to use R but being patient in doing so. And thank you Screamin Jays sandwiches outside of PLC for being so damn tasty.

abstract: Sports are a major source of revenue, culture, and enjoyment for college campuses. There is a caveat though; it is predominantly the mens side of things that brings in the big bucks, television airtime/media coverage, and ticket sales/attenance. Why may this be? Using data from (insert data set name here), I find that...
---

# Introduction

Collegiate sports are a staple in mainstream American culture. Whether it be basketball, soccer, or baseball, there's a good chance that a college has at least one of these three sports teams. With the passage of Title IX (part of the larger Educational Amendments of 1972, formally known as the "Patsy T. Mink Equal Opportunity in Education Act" since 2002), women's involvement in sports ballooned, from a meager estimate of roughly 294,105 female high school athletes in 1971 to a markedly different estimate of 3,172,637 student-athletes in 2009-10 (Cooky & Lavoi, 2012). Such a growth has fueled, and been fueled by, an increased acceptance of women in athletics; be it recreationally or professionally, the visibility and opinion on women in sports has made a marked shift since the passage of Title IX. Despite the rapid shift in opinion, media coverage (and subsequently, revenue) has still lagged behind. "Women are underrepresented in print and broadcast media...Duncan and Messner's (1994) study of  126  local  newscasts  which  aired during three two-week periods in the Los Angeles (television) market revealed that 70 percent of the local sportscasts contained no coverage of women's sports" (Tuggle, 1997). 

This study hopes to ask (and answer) questions about media coverage, attendance, and revenues as well as questions of relative team strength and leadership/ job opportunities. I ask the following: 1) How does media coverage for UO women's sports compare to similar sports for men? (Time, resources spent, appearances, mediums used and quantity) 2) How does media coverage relate to attendance and fan support at UO events? (Does a team that gets promoted and seen more really have noticable attendance boosts? Is this true for men and women?) 2b) How is revenue affected by media exposure/lack thereof? (Potential interaction(s) between RQ2 and RQ3?) 3) What is the effect of being a "good" or "bad" team on media exposure, especially for women? (Will a stellar women's team get as much attention as a terrible men's team?) 4) Do women who are former athletes get similar opportunities/gain credentials to be involved with sports/sports media as career options as much as men? (Professional examples would include: Announcers/commentators, television shows, radio spots, ads., etc.) 4b. How do women navigate their identity/positionality as an athlete in areas largely dominated by men? (Aside: I have the plethora of questions because I feel like this is ultimately going to be reined quite a bit so I'm just emptying my brain, the questions go from micro and doable to macro and potentially unfeasible/not for this class)

While studies have been done on the increased acceptance and opportunites for women in athletics as well as women professional athletes, very little has been said or focused on the attention, coverage, and revenue associated with college athletics. The subject matter becomes contentious for researchers and institutions for two reasons. One is that this research may unearth potentially unwelcome or unpleasant statistics about a particular institution or organizations as a whole. It is likely that the schools do not wish to fund research that could cast them in an unappealing manner. Additionally, college athletics remain an ethical dilemma with regards to compensation and the forms in which it takes; an "objective" study containing results that may sway public opinion against the instiutions is not likely to be seen favorably or supported by the bureaucratic powers. The study hopes to serve as a tie between media studies and sociology of sports, especially with regards to gender and culture.

As cited above, Cooky and Lavoi (2012) have found that Title IX has been effective in increasing participation in sports for women; however, women are still given much less attention than men and when they do receive it, is often in the form of hypersexualization. Tuggle (1997) wrote on the lack of media coverage afforded to women's athletics, describing how ESPN's "SportsCenter" and CNN's "Sports Tonight" aired more stories about men, a larger variety of sports for men, more team-based sports and accomplishments for men, and devoted more time per story to men. Women interviewed in the stories were few and far between and often were only on television for brief segments. Messner's 2010 chapter on mass media and sports titled "Gender in Televised Sports: News and Highlight Shows, 1989-2009" describes women's sports as literally being on the periphery of the screen via "tickers" and boxed off segments showing scores and one-sentence (if that) summaries while hosts discuss men's sports. Blinde, Taub, and Han's 1994 piece in the Sociology of Sport Journal named "Sport as a Site for Women's Group and Societal Empowerment: Perspectives From the College Athlete" notes that women involved in collegiate sports simultaneously challenge cultural and societal gender norms while also recognizing gender inequality in their own sports and lives, yet also buy in to how the media portrays them in attempts to gain exposure and distance themselves from the label of "feminist." I believe that these can all be tied together through intersectional and quantitative lenses. With readily available datasets on UO's websites and rosters of current and former players available, this approach will attempt to continue and propel the narrative of gender inequality in sports media forward into the 2020s.

# Data and Methods
The data collected for this project was hand-picked from one of six universities in the PAC-10/12: the University of Washington, Washington State University, Oregon State University, the University of Oregon, UCLA, and USC. This data was collected by scraping each colleges' mens' and womens' basketball website over the course of the past few months. From each website, I was able to collect 10 years of records, including the teams' wins and losses, tournament results, and attendance. Revenue was also readily available on each respective schools' athletic department website. When schools did not provide that information or only had a select few years of data, I used the Equity in Athletics Data Analysis database to find any missing values. Data for revenue for the current basketball season (2018-2019) is not yet available as the schools are not required to report it yet, per NCAA guidelines and rules. This dataset is extensive in that it covers the past 10 years yet is not all-inclusive as it could be extended further into the past should the information be provided/discovered. While only generalizable to basketball in the PAC-12, datasets exist of all sports offered at all competing schools within the NCAA, regardless of division. Thus, in the future, it is not unreasonable to think that a larger analysis of other sports offered to both sexes could be accomplished. 
# Results

# Conclusions

# References
